idf_component_register(
    SRCS
        "main.c"
        "mailman/i2c_task.c"
        "mailman/ap33772s.c"
        "mailman/ads7142.c"
        "mailman/TMP110.c"
        "switchboard/user_input.c"
        "composer/buzzer.c"
        "fireman/fireman.c"
        "wiseman/wiseman.c"
    "director/director.c"
        "director/GUI/HeaterGUI_gen.c"
        "director/GUI/HeaterGUI.c"
        "director/GUI/ui.c"
        "director/GUI/screens/home_gen.c"
        "director/GUI/images/channel_bg_data.c"
        "director/GUI/images/page_bg_data.c"
        "director/GUI/images/start_bg_data.c"
        "director/GUI/images/target_bg_data.c"
        "director/GUI/images/info_bg_data.c"
        "director/GUI/fonts/LaugeGothic_mode_ttf_data.c"
        "director/GUI/components/channel/channel_gen.c"
        "director/GUI/components/column/column_gen.c"
        "director/GUI/components/control/control_gen.c"
        "director/GUI/components/page/page_gen.c"
        "director/GUI/components/row/row_gen.c"
        "director/GUI/components/info/info_gen.c"
        "director/GUI/components/target_tmp/target_tmp_gen.c"
    INCLUDE_DIRS
        "."
        "mailman"
        "switchboard"
        "composer"
        "fireman"
        "wiseman"
    "director"
        "director/GUI"
        "director/GUI/screens" 
        "director/GUI/images" 
        "director/GUI/fonts"
        "director/GUI/components/channel/"
        "director/GUI/components/column/"
        "director/GUI/components/control/"
        "director/GUI/components/page/"
        "director/GUI/components/row/"
        "director/GUI/components/info/"
        "director/GUI/components/target_tmp/"
)

idf_build_set_property(COMPILE_OPTIONS "-DLV_CONF_PATH=\"${CMAKE_SOURCE_DIR}/main/lv_conf.h\"" APPEND)
idf_build_set_property(COMPILE_OPTIONS "-DLV_LVGL_H_INCLUDE_SIMPLE=1" APPEND)