idf_component_register(
    SRCS
        "main.c"
        "mailman/i2c_task.c"
        "mailman/ap33772s.c"
        "mailman/ads7142.c"
        "mailman/TMP110.c"
        "switchboard/switchboard.c"
        "composer/buzzer.c"
        "fireman/fireman.c"
        "wiseman/wiseman.c"
        "wiseman/wiseman_persist.c"
        "director/director.c"
        "director/HeaterGUI/HeaterGUI_gen.c"
        "director/HeaterGUI/HeaterGUI.c"
        "director/HeaterGUI/ui.c"
        "director/HeaterGUI/screens/home_gen.c"
        "director/HeaterGUI/images/channel_bg_data.c"
        "director/HeaterGUI/images/page_bg_data.c"
        "director/HeaterGUI/images/start_bg_data.c"
        "director/HeaterGUI/images/target_bg_data.c"
        "director/HeaterGUI/images/info_bg_data.c"
        "director/HeaterGUI/fonts/LaugeGothic_mode_ttf_data.c"
        "director/HeaterGUI/fonts/BIG_DIGITS.c"
        "director/HeaterGUI/fonts/MIDDLE_DIGITS.c"
        "director/HeaterGUI/fonts/SMALL_DIGITS.c"
        "director/HeaterGUI/components/channel/channel_gen.c"
        "director/HeaterGUI/components/column/column_gen.c"
        "director/HeaterGUI/components/control/control_gen.c"
        "director/HeaterGUI/components/page/page_gen.c"
        "director/HeaterGUI/components/row/row_gen.c"
        "director/HeaterGUI/components/info/info_gen.c"
        "director/HeaterGUI/components/target_tmp/target_tmp_gen.c"
        "director/HeaterGUI/components/settings/settings_gen.c"
        "director/HeaterGUI/components/power/power_gen.c"
    INCLUDE_DIRS
        "."
        "mailman"
        "switchboard"
        "composer"
        "fireman"
        "wiseman"
        "director"
        "director/HeaterGUI"
        "director/HeaterGUI/screens" 
        "director/HeaterGUI/images" 
        "director/HeaterGUI/fonts"
        "director/HeaterGUI/components/channel/"
        "director/HeaterGUI/components/column/"
        "director/HeaterGUI/components/control/"
        "director/HeaterGUI/components/page/"
        "director/HeaterGUI/components/row/"
        "director/HeaterGUI/components/info/"
        "director/HeaterGUI/components/target_tmp/"
        "director/HeaterGUI/components/settings/"
        "director/HeaterGUI/components/power/"
)

idf_build_set_property(COMPILE_OPTIONS "-DLV_CONF_PATH=\"${CMAKE_SOURCE_DIR}/main/lv_conf.h\"" APPEND)
idf_build_set_property(COMPILE_OPTIONS "-DLV_LVGL_H_INCLUDE_SIMPLE=1" APPEND)