/*
 * SPDX-FileCopyrightText: 2010-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */

#include <stdio.h>
#include <inttypes.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"

#include "driver/gpio.h"
#include "lvgl.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_ops.h"
#include "esp_lcd_panel_vendor.h"
#include "driver/spi_master.h"
#include "esp_heap_caps.h"
#include "esp_timer.h"

#include "esp_log.h"
#include <string.h>

#include "ui.h"
#include "demo_gen.h"
#include "home_gen.h"
#include "HeaterGUI_gen.h"
#include "director.h"
#include "switchboard/user_input.h"
#include "wiseman/wiseman.h"
#include "driver/ledc.h"
#include "pwm_alloc.h"

//patch -p1 < ../../lvgl_translation_fix_forward.patch
//Copilot Chat: Open in Editor Tab 

// Cached pointer to the dynamic page container (autogenerated object named "page_container")
static lv_obj_t * s_page_container = NULL;

static lv_obj_t * find_obj_by_name(lv_obj_t * root, const char * name) {
    if (!root || !name) return NULL;
    const char * n = lv_obj_get_name(root);
    if (n && strcmp(n, name) == 0) return root;
    uint32_t child_cnt = lv_obj_get_child_cnt(root);
    for (uint32_t i = 0; i < child_cnt; ++i) {
        lv_obj_t * child = lv_obj_get_child(root, i);
        lv_obj_t * found = find_obj_by_name(child, name);
        if (found) return found;
    }
    return NULL;
}

static void load_page(uint8_t page_id) {
    if (!s_page_container) return; // not ready yet
    lv_obj_clean(s_page_container);
    switch(page_id) {
        case 0: {
            lv_obj_t * row_4 = row_create(s_page_container);
            lv_obj_set_width(row_4, 141);
            lv_obj_set_height(row_4, 83);

            lv_obj_t * target_tmp_0 = target_tmp_create(row_4, &targetTemp);
            lv_obj_set_style_pad_all(target_tmp_0, 0, 0);

            lv_obj_t * row_5 = row_create(s_page_container);
            lv_obj_set_width(row_5, 141);
            lv_obj_set_height(row_5, 39);
            lv_obj_set_style_margin_top(row_5, 4, 0);

            lv_obj_t * control_0 = control_create(row_5, &command, &opTime);
            lv_obj_set_style_pad_all(control_0, 0, 0);
        } break;
        case 1: (void)info_create(s_page_container, "Page 2"); break;
        case 2: (void)info_create(s_page_container, "Page 3"); break;
        case 3: (void)info_create(s_page_container, "Page 4"); break;
        default: break;
    }
}
// We only keep the 1ms LVGL tick esp_timer. The "clock" uses an LVGL timer now.
static esp_timer_handle_t lv_tick_timer = NULL;

// op time counters
static uint8_t timer_ss = 0;
static uint8_t timer_mm = 0;
static uint8_t timer_hh = 0;

static QueueHandle_t g_button_queue = NULL; /* Provided by main (switchboard) */

// ---- tick helpers (wrap-safe) ----
// (Removed legacy debounce / emit code: switchboard handles input.)

// ===================== Display & LVGL =====================

#define PIN_NUM_MOSI 37
#define PIN_NUM_CLK  36
#define PIN_NUM_CS   35
#define PIN_NUM_DC   38
#define PIN_NUM_RST  39

#define BACKLIGHT_CONTROL_PIN   (10)

// ---------------- Backlight PWM (LEDC) ----------------
#define BACKLIGHT_LEDC_TIMER       PWM_BACKLIGHT_TIMER
#define BACKLIGHT_LEDC_MODE        LEDC_LOW_SPEED_MODE
#define BACKLIGHT_LEDC_CHANNEL     PWM_BACKLIGHT_CHANNEL
#define BACKLIGHT_LEDC_DUTY_RES    LEDC_TIMER_10_BIT   // 0..1023
#define BACKLIGHT_LEDC_FREQ_HZ     5000                // 5 kHz (no flicker)

static uint16_t s_backlight_max_duty = (1u << 10) - 1; // 1023 for 10-bit
static uint8_t  s_backlight_last_pct = 0xFF;           // force initial apply

static void backlight_pwm_init(uint8_t initial_pct) {
    // Configure timer
    const ledc_timer_config_t timer_cfg = {
        .speed_mode       = BACKLIGHT_LEDC_MODE,
        .duty_resolution  = BACKLIGHT_LEDC_DUTY_RES,
        .timer_num        = BACKLIGHT_LEDC_TIMER,
        .freq_hz          = BACKLIGHT_LEDC_FREQ_HZ,
        .clk_cfg          = LEDC_AUTO_CLK
    };
    ledc_timer_config(&timer_cfg);

    // Configure channel
    const ledc_channel_config_t ch_cfg = {
        .gpio_num       = BACKLIGHT_CONTROL_PIN,
        .speed_mode     = BACKLIGHT_LEDC_MODE,
        .channel        = BACKLIGHT_LEDC_CHANNEL,
        .intr_type      = LEDC_INTR_DISABLE,
        .timer_sel      = BACKLIGHT_LEDC_TIMER,
        .duty           = 0,
        .hpoint         = 0,
        .flags.output_invert = 0
    };
    ledc_channel_config(&ch_cfg);

    s_backlight_last_pct = 0xFF; // ensure set
    // Apply initial brightness
    uint8_t pct = initial_pct > 100 ? 100 : initial_pct;
    uint32_t duty = (pct * s_backlight_max_duty) / 100;
    ledc_set_duty(BACKLIGHT_LEDC_MODE, BACKLIGHT_LEDC_CHANNEL, duty);
    ledc_update_duty(BACKLIGHT_LEDC_MODE, BACKLIGHT_LEDC_CHANNEL);
    s_backlight_last_pct = pct;
}

static void backlight_set_brightness(uint8_t pct) {
    if (pct > 100) pct = 100;
    if (pct == s_backlight_last_pct) return; // no change
    uint32_t duty = (pct * s_backlight_max_duty) / 100;
    ledc_set_duty(BACKLIGHT_LEDC_MODE, BACKLIGHT_LEDC_CHANNEL, duty);
    ledc_update_duty(BACKLIGHT_LEDC_MODE, BACKLIGHT_LEDC_CHANNEL);
    s_backlight_last_pct = pct;
}

#define IMAGE_WIDTH  240
#define IMAGE_HEIGHT 135
#define JPG_BPP      2        // RGB565 = 2 bytes

esp_lcd_panel_handle_t panel_handle = NULL; // Global panel handle
static void *lvBuffer1;
static void *lvBuffer2;
#define draw_buffer_sz (IMAGE_WIDTH * IMAGE_HEIGHT * JPG_BPP)          // Buffer for 10 rows

static void lv_tick_cb(void* arg) {
    (void)arg;
    lv_tick_inc(1); // called every 1 ms by esp_timer
}

void lvgl_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map)
{
    esp_lcd_panel_draw_bitmap(panel_handle, area->x1, area->y1, area->x2 + 1, area->y2 + 1, px_map);
}

static bool notify_lvgl_flush_ready(esp_lcd_panel_io_handle_t panel_io, esp_lcd_panel_io_event_data_t *edata, void *user_ctx)
{
    lv_display_t *disp = (lv_display_t *)user_ctx;
    lv_disp_flush_ready(disp);
    return false;
}

void lvgl_init_display(void)
{
    lvBuffer1 = spi_bus_dma_memory_alloc(SPI2_HOST, draw_buffer_sz, 0);
    lvBuffer2 = spi_bus_dma_memory_alloc(SPI2_HOST, draw_buffer_sz, 0);

    // Initialize the SPI bus
    spi_bus_config_t buscfg = {
        .sclk_io_num = PIN_NUM_CLK,
        .mosi_io_num = PIN_NUM_MOSI,
        .miso_io_num = -1,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = draw_buffer_sz
    };
    ESP_ERROR_CHECK(spi_bus_initialize(SPI2_HOST, &buscfg, SPI_DMA_CH_AUTO));

    // Initialize panel IO
    esp_lcd_panel_io_handle_t io_handle = NULL;

    esp_lcd_panel_io_spi_config_t io_config = {
        .dc_gpio_num = PIN_NUM_DC,
        .cs_gpio_num = PIN_NUM_CS,
        .pclk_hz = 80 * 1000 * 1000, // Use 40 MHz for stability
        .spi_mode = 0,
        .trans_queue_depth = 10,
        .lcd_cmd_bits = 8,
        .lcd_param_bits = 8
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_io_spi(SPI2_HOST, &io_config, &io_handle));

    // Initialize the display panel
    esp_lcd_panel_dev_config_t panel_config = {
        .reset_gpio_num = PIN_NUM_RST,
        .color_space = LCD_RGB_ENDIAN_RGB,
        .bits_per_pixel = 16
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_st7789(io_handle, &panel_config, &panel_handle));

    // Reset and initialize the panel
    ESP_ERROR_CHECK(esp_lcd_panel_reset(panel_handle));
    ESP_ERROR_CHECK(esp_lcd_panel_init(panel_handle));
    ESP_ERROR_CHECK(esp_lcd_panel_set_gap(panel_handle, 40, 53));
    ESP_ERROR_CHECK(esp_lcd_panel_invert_color(panel_handle, true));
    ESP_ERROR_CHECK(esp_lcd_panel_mirror(panel_handle, true, false));
    ESP_ERROR_CHECK(esp_lcd_panel_swap_xy(panel_handle, true));
    ESP_ERROR_CHECK(esp_lcd_panel_disp_on_off(panel_handle, true));

    // Initialize backlight PWM using saved brightness setting
    uint8_t initial_brightness = 100; // fallback
    const wiseman_settings_t *ws = wiseman_get();
    if (ws) initial_brightness = ws->display_brightness;
    backlight_pwm_init(initial_brightness);

    // Create LVGL display
    lv_display_t *lvDisplay = lv_display_create(135, 240);
    lv_display_set_rotation(lvDisplay, LV_DISPLAY_ROTATION_90);
    lv_display_set_color_format(lvDisplay, LV_COLOR_FORMAT_RGB565); // Use RGB565
    lv_display_set_flush_cb(lvDisplay, lvgl_flush_cb);
    lv_display_set_buffers(lvDisplay, (void *)lvBuffer1, (void *)lvBuffer2, draw_buffer_sz, LV_DISPLAY_RENDER_MODE_FULL);

    const esp_lcd_panel_io_callbacks_t cbs = {
        .on_color_trans_done = notify_lvgl_flush_ready,
    };
    ESP_ERROR_CHECK(esp_lcd_panel_io_register_event_callbacks(io_handle, &cbs, lvDisplay));
}
 
// ===================== UI Clock via LVGL timer =====================
static lv_timer_t *ui_clock_timer = NULL;

static void ui_clock_cb(lv_timer_t *t) {
    (void)t;
    // update counters
    timer_ss++;
    if (timer_ss == 60) { timer_ss = 0; timer_mm++; }
    if (timer_mm == 60) { timer_mm = 0; timer_hh++; }
    if (timer_hh == 99) { timer_hh = 0; }

    // update label (safe: LVGL task)
    char text[10];
    if (timer_ss & 1)  snprintf(text, sizeof(text), "%02u %02u", timer_hh, timer_mm);
    else               snprintf(text, sizeof(text), "%02u:%02u", timer_hh, timer_mm);
    lv_subject_copy_string(&opTime, text);
}

static void director_task(void *arg)
{
    g_button_queue = (QueueHandle_t)arg;
    configASSERT(g_button_queue);
    // Initialize LVGL
    lv_init();

    // 1ms periodic esp_timer to advance LVGL tick (OK to call from timer)
    esp_timer_create_args_t periodic_timer_args = {
        .callback = &lv_tick_cb,
        .arg = NULL,
        .name = "lv_tick"
    };

    ESP_ERROR_CHECK(esp_timer_create(&periodic_timer_args, &lv_tick_timer));
    ESP_ERROR_CHECK(esp_timer_start_periodic(lv_tick_timer, 1000)); // 1000 us = 1 ms

    lvgl_init_display();

    ui_init(NULL);
    lv_obj_t * home_screen = home_create();
    lv_scr_load(home_screen);

    // Locate and cache the autogenerated container by its LVGL name
    s_page_container = find_obj_by_name(home_screen, "page_container");
    if (!s_page_container) {
        ESP_LOGW("director", "page_container not found (name may have changed in autogenerated code)");
    }

    // Create the LVGL clock timer (start paused; we control via button)
    ui_clock_timer = lv_timer_create(ui_clock_cb, 1000, NULL);
    lv_timer_pause(ui_clock_timer);

    // (Input scanning handled by switchboard module; we just consume events.)

    // State used in button handler
    bool opStat = false;
    bool chan1 = true;
    bool chan2 = true;

    // ========= Main UI task loop (sole owner of LVGL calls) =========
    uint32_t brightness_poll_elapsed_ms = 0;
    while (1) {
        // Drain button events here (replaces vConsoleTask)
        event_msg_t msg;
        while (xQueueReceive(g_button_queue, &msg, 0) == pdTRUE) {
            if (msg.event == BUTTON_EVENT_SHORT) {
                switch (msg.btn_id) {
                    case 40: { // "RIGHT_BOTTOM"
                        opStat = !opStat;
                        if (opStat) {
                            lv_subject_copy_string(&command, "STOP");
                            lv_timer_resume(ui_clock_timer);
                        } else {
                            lv_subject_copy_string(&command, "START");
                            timer_ss = timer_mm = timer_hh = 0;
                            lv_subject_copy_string(&opTime, "00:00");
                            lv_timer_pause(ui_clock_timer);
                        }
                    } break;

                    case 41: { // "RIGHT_TOP"
                        int t = lv_subject_get_int(&targetTemp);
                        t++;
                        if (t > 60) t = 60;
                        lv_subject_set_int(&targetTemp, t);
                    } break;

                    case 42: { // "RIGHT_CENTER"
                        int t = lv_subject_get_int(&targetTemp);
                        t--;
                        if (t < 0) t = 0;
                        lv_subject_set_int(&targetTemp, t);
                    } break;

                    case 45: { // "LEFT_BOTTOM"
                        int t = lv_subject_get_int(&pageSelect);
                        t++;
                        if (t > 3) t = 0;
                        lv_subject_set_int(&pageSelect, t);
                        load_page(t);
                    } break;

                    case 47: { // "LEFT_CENTER"
                        chan2 = !chan2;
                        lv_subject_copy_string(&ch2_active, chan2 ? "•" : " ");
                    } break;

                    case 48: { // "LEFT_TOP"
                        chan1 = !chan1;
                        lv_subject_copy_string(&ch1_active, chan1 ? "•" : " ");
                    } break;
                }
            } else { // BUTTON_EVENT_REPEAT
                switch (msg.btn_id) {
                    case 41: { // "RIGHT_TOP"
                        int t = lv_subject_get_int(&targetTemp);
                        t++;
                        if (t > 60) t = 60;
                        lv_subject_set_int(&targetTemp, t);
                    } break;
                    case 42: { // "RIGHT_CENTER"
                        int t = lv_subject_get_int(&targetTemp);
                        t--;
                        if (t < 0) t = 0;
                        lv_subject_set_int(&targetTemp, t);
                    } break;
                    default:
                        break;
                }
            }
        }

        // Run LVGL
        // Periodically poll brightness setting (cheap) every ~250 ms
        if ((brightness_poll_elapsed_ms += 5) >= 250) {
            brightness_poll_elapsed_ms = 0;
            const wiseman_settings_t *ws_cur = wiseman_get();
            if (ws_cur) backlight_set_brightness(ws_cur->display_brightness);
        }

        lv_timer_handler();
        vTaskDelay(pdMS_TO_TICKS(5));
    }

    vTaskDelete(NULL);
}

bool director_start(QueueHandle_t button_event_queue) {
    if (!button_event_queue) return false;
    BaseType_t ok = xTaskCreate(director_task, "director", 8192, button_event_queue, 6, NULL);
    return ok == pdPASS;
}