/*
 * SPDX-FileCopyrightText: 2010-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */

#include <stdio.h>
#include <inttypes.h>
#include <string.h>
#include <math.h>

#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "esp_log.h"

#include "driver/spi_master.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_ops.h"
#include "esp_lcd_panel_vendor.h"

#include "lvgl.h"

#include "ui.h"
#include "home_gen.h"
#include "HeaterGUI_gen.h"

#include "director.h"
#include "switchboard/switchboard.h"
#include "fireman/fireman.h"
#include "mailman/mailman.h"
#include "AP33772S.h"
#include "wiseman/wiseman.h"
#include "director/backlight.h"
#include "director/orientation.h"
#include "pinout.h"
#include "timekeeper.h"
#include "settings_page.h"
#include "power_page.h"

// ===================== DEFINITIONS AND MACROS =====================

#define IMAGE_WIDTH  240
#define IMAGE_HEIGHT 135
#define JPG_BPP      2        // RGB565 = 2 bytes
#define draw_buffer_sz (IMAGE_WIDTH * IMAGE_HEIGHT * JPG_BPP)          // Buffer for 10 rows

// ===================== ENUMS AND TYPEDEFS =====================
lv_obj_t * find_obj_by_name(lv_obj_t * root, const char * name);
// Page order must match the order we cycle through with LEFT_BOTTOM button.
// The original switch in load_page treated case 1 as settings and case 2 as power, but
// the enum previously had POWER before SETTINGS which prevented page_settings() from running.
// Fix: define enum in the actual visual order: MAIN -> SETTINGS -> POWER -> INFO.
enum {
    PAGE_MAIN = 0,
    PAGE_SETTINGS,
    PAGE_POWER,
    PAGE_INFO,
    PAGE_COUNT
};

// ===================== GLOBAL VARIABLES =====================

esp_lcd_panel_handle_t panel_handle = NULL; // Global panel handle

uint8_t opStat = 0; // 0=stopped, 1=running

// ===================== STATIC VARIABLES =====================

// Cached pointer to the dynamic page container (autogenerated object named "page_container")
static lv_obj_t * s_page_container = NULL; // container for dynamic pages

// Display sleep state
static bool s_display_sleeping = false;       // true when dimmed due to inactivity
static TickType_t s_last_input_tick = 0;      // last button activity (for inactivity timer)

// Timer edit mode state
static bool s_timer_edit_mode = false;        // true when editing timer duration
#define TIMER_EDIT_HOLD_MS 3000                // 3 second hold to enter edit mode

// We only keep the 1ms LVGL tick esp_timer. The "clock" uses an LVGL timer now.
static esp_timer_handle_t lv_tick_timer = NULL;

static QueueHandle_t g_button_queue = NULL; /* Provided by main (switchboard) */
static QueueHandle_t g_jumbo_queue  = NULL; /* Fireman sample queue */
static QueueHandle_t g_i2c_queue    = NULL; /* Mailman I2C queue */

// No longer requesting PD caps at runtime; we receive a snapshot at startup.
static ap33772s_caps_t g_initial_pd_caps = {0};

static lv_display_t *s_lvgl_display = NULL;  // Global reference to LVGL display

static void *lvBuffer1;
static void *lvBuffer2;

// UI Clock via LVGL timer
// static lv_timer_t *ui_clock_timer = NULL;
static lv_timer_t *settings_blink_timer = NULL; // runs independent of op clock
static lv_timer_t *sleep_check_timer = NULL;    // checks inactivity for display sleep

// ===================== FORWARD DECLARATIONS =====================

void page_main(event_msg_t msg);
void page_info(event_msg_t msg);

static void load_page(uint8_t page_id);
static void unload_page(uint8_t page_id);
static void lv_tick_cb(void* arg);
// static void ui_clock_cb(lv_timer_t *t);
static void display_apply_user_brightness(void);
static void sleep_check_cb(lv_timer_t *t);
static bool request_pd_voltage(uint8_t voltage);
static void director_task(void *arg);

void lvgl_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map);
static bool notify_lvgl_flush_ready(esp_lcd_panel_io_handle_t panel_io, esp_lcd_panel_io_event_data_t *edata, void *user_ctx);
void lvgl_init_display(void);

// ===================== FUNCTION IMPLEMENTATIONS =====================

lv_obj_t * find_obj_by_name(lv_obj_t * root, const char * name) {
    if (!root || !name) return NULL;
    const char * n = lv_obj_get_name(root);
    if (n && strcmp(n, name) == 0) return root;
    uint32_t child_cnt = lv_obj_get_child_cnt(root);
    for (uint32_t i = 0; i < child_cnt; ++i) {
        lv_obj_t * child = lv_obj_get_child(root, i);
        lv_obj_t * found = find_obj_by_name(child, name);
        if (found) return found;
    }
    return NULL;
}

static lv_obj_t * page_main_create(lv_obj_t * parent) {
    lv_obj_t * row_4 = row_create(parent);
    lv_obj_set_width(row_4, 141);
    lv_obj_set_height(row_4, 83);

    lv_obj_t * target_tmp_0 = target_tmp_create(row_4, &targetTemp);
    lv_obj_set_style_pad_all(target_tmp_0, 0, 0);

    lv_obj_t * row_5 = row_create(parent);
    lv_obj_set_width(row_5, 141);
    lv_obj_set_height(row_5, 39);
    lv_obj_set_style_margin_top(row_5, 4, 0);

    lv_obj_t * control_0 = control_create(row_5, &command, &opTime);
    lv_obj_set_style_pad_all(control_0, 0, 0);
    
    return row_4; // Return first row as representative object
}

static void load_page(uint8_t page_id) {
    if (!s_page_container) return; // not ready yet
    lv_obj_clean(s_page_container);
    lv_subject_set_int(&pageSelect, (int)page_id);
    switch(page_id) {
        case PAGE_MAIN: {
            (void)page_main_create(s_page_container);
        } break;
        case PAGE_SETTINGS: {
            page_settings_create(s_page_container);
        } break;
        case PAGE_POWER: {
            page_power_create(s_page_container, &g_initial_pd_caps);
        } break;
        case PAGE_INFO: {
            (void)info_create(s_page_container);
        } break;
        default: break;
    }
}

static void unload_page(uint8_t page_id) {
    switch(page_id) {
        case PAGE_MAIN: {
            //clean up page 1 resources if any
        } break;
        case PAGE_POWER: {
            page_power_cleanup();
        } break;
        case PAGE_SETTINGS: {
            page_settings_cleanup();
        } break;
        case PAGE_INFO: {
            //clean up page 4 resources if any
        } break;
        default: break;
    }
}   

static void lv_tick_cb(void* arg) {
    (void)arg;
    lv_tick_inc(1); // called every 1 ms by esp_timer
}

void lvgl_flush_cb(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map) {
    esp_lcd_panel_draw_bitmap(panel_handle, area->x1, area->y1, area->x2 + 1, area->y2 + 1, px_map);
}

static bool notify_lvgl_flush_ready(esp_lcd_panel_io_handle_t panel_io, esp_lcd_panel_io_event_data_t *edata, void *user_ctx) {
    lv_display_t *disp = (lv_display_t *)user_ctx;
    lv_disp_flush_ready(disp);
    return false;
}

void lvgl_init_display(void)
{
    // 1ms periodic esp_timer to advance LVGL tick (OK to call from timer)
    esp_timer_create_args_t periodic_timer_args = {
        .callback = &lv_tick_cb,
        .arg = NULL,
        .name = "lv_tick"
    };

    ESP_ERROR_CHECK(esp_timer_create(&periodic_timer_args, &lv_tick_timer));
    ESP_ERROR_CHECK(esp_timer_start_periodic(lv_tick_timer, 1000)); // 1000 us = 1 ms

    lvBuffer1 = spi_bus_dma_memory_alloc(SPI2_HOST, draw_buffer_sz, 0);
    lvBuffer2 = spi_bus_dma_memory_alloc(SPI2_HOST, draw_buffer_sz, 0);

    // Initialize the SPI bus
    spi_bus_config_t buscfg = {
        .sclk_io_num = DISPLAY_SCK,
        .mosi_io_num = DISPLAY_MOSI,
        .miso_io_num = -1,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = draw_buffer_sz
    };
    ESP_ERROR_CHECK(spi_bus_initialize(SPI2_HOST, &buscfg, SPI_DMA_CH_AUTO));

    // Initialize panel IO
    esp_lcd_panel_io_handle_t io_handle = NULL;

    esp_lcd_panel_io_spi_config_t io_config = {
        .dc_gpio_num = DISPLAY_RS,
        .cs_gpio_num = DISPLAY_CS,
        .pclk_hz = 80 * 1000 * 1000, // Use 40 MHz for stability
        .spi_mode = 0,
        .trans_queue_depth = 10,
        .lcd_cmd_bits = 8,
        .lcd_param_bits = 8
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_io_spi(SPI2_HOST, &io_config, &io_handle));

    // Initialize the display panel
    esp_lcd_panel_dev_config_t panel_config = {
        .reset_gpio_num = DISPLAY_RST,
        .color_space = LCD_RGB_ENDIAN_RGB,
        .bits_per_pixel = 16
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_st7789(io_handle, &panel_config, &panel_handle));

    // Reset and initialize the panel
    ESP_ERROR_CHECK(esp_lcd_panel_reset(panel_handle));
    ESP_ERROR_CHECK(esp_lcd_panel_init(panel_handle));
    ESP_ERROR_CHECK(esp_lcd_panel_set_gap(panel_handle, 40, 52));
    ESP_ERROR_CHECK(esp_lcd_panel_invert_color(panel_handle, true));
    ESP_ERROR_CHECK(esp_lcd_panel_mirror(panel_handle, true, false));
    ESP_ERROR_CHECK(esp_lcd_panel_swap_xy(panel_handle, true));
    // Display will be turned on after initial screen is rendered
    ESP_ERROR_CHECK(esp_lcd_panel_disp_on_off(panel_handle, false));

    // Initialize backlight PWM using saved brightness setting
    uint8_t initial_brightness = 100; // fallback
    const wiseman_settings_t *ws = wiseman_get();
    if (ws) initial_brightness = ws->display_brightness;
    if (initial_brightness < 5) { // enforce minimum so user cannot soft-brick UI visibility
        initial_brightness = 5;
        wiseman_set_display_brightness(initial_brightness);
    }
    backlight_init(initial_brightness);
    // Create LVGL display
    lv_display_t *lvDisplay = lv_display_create(135, 240);
    s_lvgl_display = lvDisplay; // Store global reference for runtime rotation
    lv_display_set_rotation(lvDisplay, LV_DISPLAY_ROTATION_90);
    lv_display_set_color_format(lvDisplay, LV_COLOR_FORMAT_RGB565); // Use RGB565
    lv_display_set_flush_cb(lvDisplay, lvgl_flush_cb);
    lv_display_set_buffers(lvDisplay, (void *)lvBuffer1, (void *)lvBuffer2, draw_buffer_sz, LV_DISPLAY_RENDER_MODE_FULL);

    const esp_lcd_panel_io_callbacks_t cbs = {
        .on_color_trans_done = notify_lvgl_flush_ready,
    };
    ESP_ERROR_CHECK(esp_lcd_panel_io_register_event_callbacks(io_handle, &cbs, lvDisplay));
    
    
    // Initialize orientation detection and set initial display orientation  
    orientation_init(s_lvgl_display, panel_handle);
}

// Apply the user's configured brightness to the hardware backlight
static void display_apply_user_brightness(void) {
    int b = lv_subject_get_int(&brightness);
    if (b < 5) b = 5; else if (b > 100) b = 100; // user brightness minimum
    backlight_set_brightness((uint8_t)b);
}

// Periodically check inactivity and dim the display according to sleepTimer
static void sleep_check_cb(lv_timer_t *t) {
    (void)t;
    int st = lv_subject_get_int(&sleepTimer); // seconds; 0=OFF
    if (st <= 0) {
        // Sleep disabled; ensure we're awake
        if (s_display_sleeping) {
            display_apply_user_brightness(); // already clamps to >=5
            s_display_sleeping = false;
        }
        return;
    }

    TickType_t now = xTaskGetTickCount();
    TickType_t idle_ticks = now - s_last_input_tick;
    uint32_t idle_ms = (uint32_t)idle_ticks * portTICK_PERIOD_MS;

    if (!s_display_sleeping) {
        if (idle_ms >= (uint32_t)st * 1000U) {
            // Dim display (do not change UI subject so user brightness is preserved)
            backlight_set_brightness(0);
            s_display_sleeping = true;
        }
    }
}

/* Helper: request PD voltage change through mailman */
static bool request_pd_voltage(uint8_t voltage) {
    if (!g_i2c_queue || (voltage != 5 && voltage != 9 && voltage != 15 && voltage != 20)) {
        return false;
    }
    i2c_msg_t msg = {0};
    msg.type = I2C_MSG_PD_SET_PDO;
    msg.data.pd_set.set_voltage = voltage;
    QueueHandle_t resp = xQueueCreate(1, sizeof(bool));
    if (!resp) return false;
    msg.response_queue = resp;
    bool ok = false;
    if (xQueueSend(g_i2c_queue, &msg, pdMS_TO_TICKS(50)) == pdTRUE) {
        if (xQueueReceive(resp, &ok, pdMS_TO_TICKS(200)) == pdTRUE) {
            // Success - response received
        } else {
            ok = false; // timeout
        }
    }
    vQueueDelete(resp);
    return ok;
}

static void director_task(void *arg)
{
    (void)arg; // unused parameter

    configASSERT(g_button_queue);
    // Initialize LVGL
    lv_init();

    lvgl_init_display();

    ui_init(NULL);

    lv_obj_t * home_screen = home_create();
    lv_scr_load(home_screen);
    
    // Force LVGL to render the initial screen before enabling display
    lv_timer_handler();
    
    // Now turn on the display with clean content
    ESP_ERROR_CHECK(esp_lcd_panel_disp_on_off(panel_handle, true));

    // Locate and cache the autogenerated container by its LVGL name
    s_page_container = find_obj_by_name(home_screen, "page_container");
    if (!s_page_container) {
        ESP_LOGW("director", "page_container not found (name may have changed in autogenerated code)");
    }

    // Create always-on blink timer for Settings selection (faster blink)
    settings_blink_timer = lv_timer_create(settings_page_blink_cb, 500, NULL);

    // Initialize last input time and create inactivity sleep checker
    s_last_input_tick = xTaskGetTickCount();
    sleep_check_timer = lv_timer_create(sleep_check_cb, 250, NULL);

    // Sync wiseman persistent settings to LVGL UI subjects
    wiseman_sync_to_ui();
    
    // State used in button handler
    uint8_t current_page = PAGE_MAIN;
    
    // start with home page
    load_page(PAGE_MAIN);
    while (1) {
        // Drain button events here (replaces vConsoleTask)
        event_msg_t msg;
        while (xQueueReceive(g_button_queue, &msg, 0) == pdTRUE) {
            // Remap button ID based on display orientation
            uint8_t original_btn_id = msg.btn_id;
            msg.btn_id = orientation_remap_button(msg.btn_id);
            
            ESP_LOGD("director.btn", "btn id=%d->%d event=%d page=%u flipped=%d", 
                     original_btn_id, msg.btn_id, msg.event, current_page, orientation_is_flipped());
            
            // Update inactivity timer and handle wake on any button while sleeping
            s_last_input_tick = xTaskGetTickCount();

            if (s_display_sleeping) {
                ESP_LOGD("director.sleep", "Wake on button press (id=%d)", msg.btn_id);
                display_apply_user_brightness();
                s_display_sleeping = false;
                // Ignore this event so the first press only wakes the display
                continue;
            }

            if(msg.btn_id == BUTTON_LEFT_BOTTOM) { // "LEFT_BOTTOM"
                if (msg.event == BUTTON_EVENT_SHORT || msg.event == BUTTON_EVENT_REPEAT) {
                    uint8_t next = (current_page + 1) % PAGE_COUNT;
                    if (next != current_page) {
                        unload_page(current_page);                        
                        load_page(next);
                        current_page = next;
                    }
                }
            }else{
                // Other buttons handled in page-specific functions
                switch(current_page) {
                    case PAGE_MAIN:     page_main(msg); break;
                    case PAGE_POWER:    power_page_handle_event(msg); break;
                    case PAGE_SETTINGS: settings_page_handle_event(msg); break;
                    case PAGE_INFO:     page_info(msg); break;
                    default: break;
                }
            }
        }
        
        // Display temperature updates from fireman module
        if (g_jumbo_queue) {
            fireman_sample_t latest;
            if (xQueueReceive(g_jumbo_queue, &latest, 0) == pdTRUE) {
                bool noData = isnan(latest.ch1) || isnan(latest.ch2);
                if (noData) {
                    lv_subject_set_int(&ch1_temp_big, 0);
                    lv_subject_set_int(&ch1_temp_small, 0);
                    lv_subject_set_int(&ch2_temp_big, 0);
                    lv_subject_set_int(&ch2_temp_small, 0);
                } else {
                    float t1 = latest.ch1; if (t1 < 0) t1 = 0;
                    int t1_whole = (int)t1;
                    int t1_dec = (int)((t1 - (float)t1_whole) * 10.0f + 0.0001f);
                    if (t1_dec < 0) t1_dec = 0; else if (t1_dec > 9) t1_dec = 9;
                    lv_subject_set_int(&ch1_temp_big, t1_whole);
                    lv_subject_set_int(&ch1_temp_small, t1_dec);

                    float t2 = latest.ch2; if (t2 < 0) t2 = 0;
                    int t2_whole = (int)t2;
                    int t2_dec = (int)((t2 - (float)t2_whole) * 10.0f + 0.0001f);
                    if (t2_dec < 0) t2_dec = 0; else if (t2_dec > 9) t2_dec = 9;
                    lv_subject_set_int(&ch2_temp_big, t2_whole);
                    lv_subject_set_int(&ch2_temp_small, t2_dec);
                }
                // No semaphore give needed
            }
        }

        lv_timer_handler();
        
        // Check tilt pin and update display orientation if needed
        orientation_check_and_update();
        
        // Check if timer finished (safe context, no ISR)
        if (timekeeper_did_timer_finish()) {
            opStat = false;
            fireman_set_heater1_enabled(false);
            fireman_set_heater2_enabled(false);
            // Revert PD voltage to 5V
            bool ok = request_pd_voltage(5);
            ESP_LOGI("director.timer", "Timer elapsed - heaters disabled, PD reverted to 5V (result=%d)", (int)ok);
            if (ok) lv_subject_set_int(&activePDO, 5);
        }
        
        // Update runtime display approximately once per loop (10ms delay below) but only when minute count changes.
        static uint32_t s_last_runtime_min = 0xFFFFFFFFu; // force first update
        uint32_t cur_min = wiseman_get_op_time_minutes();

        if (cur_min != s_last_runtime_min) {
            s_last_runtime_min = cur_min;
            // UI expects hours (integer). Convert minutes -> hours (truncate)
            uint32_t hours = cur_min / 60u;
            lv_subject_set_int(&runTime, (int)hours);
        }

        // Slightly longer delay to ensure IDLE gets time (watchdog feed)
        vTaskDelay(pdMS_TO_TICKS(10));
    }

    vTaskDelete(NULL);
}

// Callback invoked by timekeeper when the timer elapses
static void timer_elapsed_callback(void) {
    // Timer has finished: stop the heaters and update UI state
    opStat = false;
    fireman_set_heater1_enabled(false);
    fireman_set_heater2_enabled(false);
    // Revert PD voltage to 5V
    bool ok = request_pd_voltage(5);
    ESP_LOGI("director.timer", "Timer elapsed - heaters disabled, PD reverted to 5V (result=%d)", (int)ok);
    if (ok) lv_subject_set_int(&activePDO, 5);
}

bool director_init(QueueHandle_t button_event_queue, QueueHandle_t sample_queue, QueueHandle_t i2c_queue, const ap33772s_caps_t *initial_pd_caps) {

    // Set global variables directly
    g_button_queue = button_event_queue;
    g_jumbo_queue  = sample_queue;
    g_i2c_queue    = i2c_queue;
    
    if (initial_pd_caps) {
        g_initial_pd_caps = *initial_pd_caps;
    } else {
        memset(&g_initial_pd_caps, 0, sizeof(g_initial_pd_caps));
        ESP_LOGW("director.pd", "No PD caps provided - all voltages unavailable");
    }

    // Note: UI updates moved to director_task after LVGL initialization

    timekeeper_init(NULL);

    BaseType_t ok = xTaskCreate(director_task, "director", 12288, NULL, 6, NULL);
    return (ok == pdPASS);
}

void page_main(event_msg_t msg){
    // Check if timer mode is enabled in wiseman
    const wiseman_settings_t* settings = wiseman_get();
    bool timer_mode_enabled = (settings && settings->timer_mode);
    
    if (msg.event == BUTTON_EVENT_SHORT) {
        // Clear any pending long-press detection on short press
        if (msg.btn_id == BUTTON_RIGHT_BOTTOM && s_timer_edit_mode) {
            // In edit mode: exit on bottom-right short press
            timekeeper_timer_stop_edit();
            s_timer_edit_mode = false;
        } else if (s_timer_edit_mode) {
            // In edit mode: handle increment/decrement buttons
            if (msg.btn_id == BUTTON_LEFT_TOP) {
                timekeeper_increment_hour();
            } else if (msg.btn_id == BUTTON_LEFT_CENTER) {
                timekeeper_decrement_hour();
            } else if (msg.btn_id == BUTTON_RIGHT_TOP) {
                timekeeper_increment_minute();
            } else if (msg.btn_id == BUTTON_RIGHT_CENTER) {
                timekeeper_decrement_minute();
            }
            return; // Don't process other button logic while in edit mode
        } else if (msg.btn_id == BUTTON_RIGHT_BOTTOM) {
            // Not in timer edit mode: normal start/stop logic
            opStat = !opStat;
                if (opStat) {                    
                    // lv_timer_resume(ui_clock_timer);
                    timekeeper_start();
                    // START pressed: configure heaters
                    int target = lv_subject_get_int(&targetTemp);
                    if (target < 0) target = 0; else if (target > 60) target = 60;
                    // Apply the same target to both internal PID controllers for now
                    fireman_set_setpoints(target, target);
                    // Determine which channels to enable based on activeCh selection
                    const char* chsel = lv_subject_get_string(&activeCh);
                    bool en1 = false, en2 = false;
                    if (chsel) {
                        if (strcmp(chsel, "CH1") == 0) { en1 = true; en2 = false; }
                        else if (strcmp(chsel, "CH2") == 0) { en1 = false; en2 = true; }
                        else { en1 = true; en2 = true; } // "CH1/2" or fallback
                    } else { en1 = true; en2 = true; }
                    fireman_set_heater1_enabled(en1);
                    fireman_set_heater2_enabled(en2);
                    // Request higher PD voltage (20V preferred, else 15V) if available snapshot indicates support
                    ap33772s_caps_t caps_snapshot = g_initial_pd_caps; // startup snapshot
                    uint8_t desired = 0;
                    if (caps_snapshot.twentyV) desired = 20; else if (caps_snapshot.fifteenV) desired = 15; else desired = 0;
                    if (desired) {
                        bool ok = request_pd_voltage(desired);
                        // If 20V failed and we tried it first, optionally fall back to 15V if available
                        if (!ok && desired == 20 && g_initial_pd_caps.fifteenV) {
                            ok = request_pd_voltage(15);
                            if (ok) desired = 15; // reflect fallback voltage
                        }
                        ESP_LOGI("director.pd", "START PD request -> target=%uV result=%d", (unsigned)desired, (int)ok);
                        if (ok) lv_subject_set_int(&activePDO, desired);
                    } else {
                        ESP_LOGI("director.pd", "START no higher PD voltage available (stay at 5V)");
                    }
                    ESP_LOGI("director.heaters", "Heaters START target=%dC ch1=%d ch2=%d", target, en1, en2);
                } else {                    
                    timekeeper_stop();  
                    // STOP pressed: disable both heaters (setpoints retained for next start)
                    fireman_set_heater1_enabled(false);
                    fireman_set_heater2_enabled(false);
                    // Revert PD voltage to 5V (ignore failure)
                    bool ok = request_pd_voltage(5);
                    ESP_LOGI("director.pd", "STOP PD request 5V result=%d", (int)ok);
                    if (ok) lv_subject_set_int(&activePDO, 5);
                    ESP_LOGI("director.heaters", "Heaters STOP (disabled all)");
                }
        } else if (msg.btn_id == BUTTON_RIGHT_TOP) {
            // INCREMENT temperature (short press)
            int t = lv_subject_get_int(&targetTemp) + 1;
            if (t < 61) {
                lv_subject_set_int(&targetTemp, t);
                // Live update while running
                if (opStat) {
                    int clamped = t; if (clamped < 0) clamped = 0; else if (clamped > 60) clamped = 60;
                    fireman_set_setpoints(clamped, clamped);
                }
            }
        } else if (msg.btn_id == BUTTON_RIGHT_CENTER) {
            // DECREMENT temperature (short press)
            int t = lv_subject_get_int(&targetTemp) - 1;
            if (t > -1) {
                lv_subject_set_int(&targetTemp, t);
                // Live update while running
                if (opStat) {
                    int clamped = t; if (clamped < 0) clamped = 0; else if (clamped > 60) clamped = 60;
                    fireman_set_setpoints(clamped, clamped);
                }
            }
        }
    } else if (msg.event == BUTTON_EVENT_REPEAT) {
        switch (msg.btn_id) {
            case BUTTON_RIGHT_TOP: { // "RIGHT_TOP" (increment hold)
                if (!s_timer_edit_mode) {
                    int t = lv_subject_get_int(&targetTemp) + 1;
                    if (t < 61) {
                        lv_subject_set_int(&targetTemp, t);
                        if (opStat) {
                            int clamped = t; if (clamped < 0) clamped = 0; else if (clamped > 60) clamped = 60;
                            fireman_set_setpoints(clamped, clamped);
                        }
                    }
                }
            } break;

            case BUTTON_RIGHT_CENTER: { // "RIGHT_CENTER" (decrement hold)
                if (!s_timer_edit_mode) {
                    int t = lv_subject_get_int(&targetTemp) - 1;
                    if (t > -1) {
                        lv_subject_set_int(&targetTemp, t);
                        if (opStat) {
                            int clamped = t; if (clamped < 0) clamped = 0; else if (clamped > 60) clamped = 60;
                            fireman_set_setpoints(clamped, clamped);
                        }
                    }
                }
            } break;
            
            case BUTTON_RIGHT_BOTTOM: { // "RIGHT_BOTTOM" (long hold to enter timer edit)
                static uint8_t count = 0;
                if(count == 3){ // after 5 repeats (~3s)
                    if (timer_mode_enabled && !s_timer_edit_mode) {
                        timekeeper_timer_start_edit();
                        s_timer_edit_mode = true;
                        ESP_LOGI("director.timer", "Entered timer edit mode");
                    }
                    count = 0; // reset count
                }
                count++;
            } break;
        }
    }
}

void page_info(event_msg_t msg){
    // No button events handled on this page currently
    (void)msg;
}