#include "power_page.h"
#include "ui.h"
#include "power_gen.h"
#include <stdio.h>

void page_power_create(lv_obj_t *page_container, const ap33772s_caps_t *pd_caps) {
    if (!page_container || !pd_caps) return;

    // Create the autogenerated power page UI
    (void)power_create(page_container);

    // Update PD capabilities in UI
    lv_subject_set_int(&fiveV_available,    pd_caps->fiveV);
    lv_subject_set_int(&nineV_available,    pd_caps->nineV);
    lv_subject_set_int(&fifteenV_available, pd_caps->fifteenV);
    lv_subject_set_int(&twentyV_available,  pd_caps->twentyV);
    
    // Set active PDO based on PD availability
    if (pd_caps->fiveV) {
        // PD charger available - default to 5V
        lv_subject_set_int(&activePDO, 5);
    } else {
        // Not a PD charger - set to 0 (no PD)
        lv_subject_set_int(&activePDO, 0);
    }
    
    // Update current ratings
    char buf[10];
    if (pd_caps->fiveV) {
        snprintf(buf, sizeof(buf), "%.2fA", pd_caps->cur5);
        lv_subject_copy_string(&fiveV, buf);
    } else {
        lv_subject_copy_string(&fiveV, "--");
    }
    
    if (pd_caps->nineV) {
        snprintf(buf, sizeof(buf), "%.2fA", pd_caps->cur9);
        lv_subject_copy_string(&nineV, buf);
    } else {
        lv_subject_copy_string(&nineV, "--");
    }
    
    if (pd_caps->fifteenV) {
        snprintf(buf, sizeof(buf), "%.2fA", pd_caps->cur15);
        lv_subject_copy_string(&fifteenV, buf);
    } else {
        lv_subject_copy_string(&fifteenV, "--");
    }
    
    if (pd_caps->twentyV) {
        snprintf(buf, sizeof(buf), "%.2fA", pd_caps->cur20);
        lv_subject_copy_string(&twentyV, buf);
    } else {
        lv_subject_copy_string(&twentyV, "--");
    }
}

void power_page_handle_event(event_msg_t msg) {
    // No button events handled on this page for now
    (void)msg;
}

void page_power_cleanup(void) {
    // No cleanup needed for power page currently
}
