#!/usr/bin/env python3
"""Quick heuristic stats for code origin categories.

We classify lines into buckets:
  - ai: lines containing markers that Copilot / AI often emits (e.g. 'Generated by', 'AI', 'autogenerated')
  - tool: lines that look like build system / generated artifacts (e.g. *_gen.c, comments with 'DO NOT EDIT', 'Automatically generated')
  - human: everything else (only for source-like files we scan)

This is purely heuristic; it does NOT guarantee correctness. Adjust patterns as needed.

Usage (from repo root):
  python scripts/code_origin_stats.py

Optional args:
  --extensions .c,.h,.cpp,.py  (comma separated list to include)
  --limit 500  (max files)

The script deliberately skips the build/ directory and common binary artifacts.
"""
from __future__ import annotations
import argparse
import os
import re
from pathlib import Path
from typing import List, Dict

AI_PATTERNS = [
    re.compile(r"generated\s+by\s+ai", re.I),
    re.compile(r"ai-?assistant", re.I),
    re.compile(r"copilot", re.I),
]

TOOL_PATTERNS = [
    re.compile(r"do not edit", re.I),
    re.compile(r"auto-?generated", re.I),
    re.compile(r"automatically generated", re.I),
    re.compile(r"generated file", re.I),
]

# Filenames that imply tool generation
FILENAME_GEN_HINTS = ("_gen.", ".pb.c", ".pb.h", "CMakeFiles", "build-preview")

SKIP_DIRS = {"build", "esp-idf", ".git", "__pycache__"}
DEFAULT_EXTS = {".c", ".h", ".cpp", ".hpp", ".py", ".cmake"}


def classify_line(line: str) -> str | None:
    l = line.strip()
    if not l:
        return None  # don't count blank lines
    for pat in AI_PATTERNS:
        if pat.search(l):
            return "ai"
    for pat in TOOL_PATTERNS:
        if pat.search(l):
            return "tool"
    return "human"


def classify_file(file_path: Path, exts: set[str]) -> Dict[str, int]:
    origin_counts = {"ai": 0, "tool": 0, "human": 0}
    try:
        text = file_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return origin_counts
    for line in text.splitlines():
        bucket = classify_line(line)
        if bucket:
            origin_counts[bucket] += 1
    # If filename hints at generation, re-weight: move all human lines to tool if no AI lines
    if any(hint in file_path.name for hint in FILENAME_GEN_HINTS):
        if origin_counts["ai"] == 0 and origin_counts["human"] > 0:
            origin_counts["tool"] += origin_counts["human"]
            origin_counts["human"] = 0
    return origin_counts


def scan(root: Path, exts: set[str], limit: int | None) -> Dict[str, int]:
    totals = {"ai": 0, "tool": 0, "human": 0}
    count_files = 0
    for dirpath, dirnames, filenames in os.walk(root):
        # Prune skip dirs
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fname in filenames:
            fpath = Path(dirpath) / fname
            if fpath.suffix not in exts:
                continue
            counts = classify_file(fpath, exts)
            for k, v in counts.items():
                totals[k] += v
            count_files += 1
            if limit and count_files >= limit:
                return totals
    return totals


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--extensions', type=str, default=','.join(sorted(DEFAULT_EXTS)), help='Comma separated list of extensions to include')
    ap.add_argument('--limit', type=int, default=None, help='Optional file limit for faster runs')
    args = ap.parse_args()
    exts = {e if e.startswith('.') else f'.{e}' for e in args.extensions.split(',') if e}
    root = Path.cwd()
    totals = scan(root, exts, args.limit)
    grand_total = sum(totals.values()) or 1
    print('Code origin heuristic statistics:')
    for k in ("ai", "tool", "human"):
        pct = (totals[k] / grand_total) * 100.0
        print(f"  {k:5s}: {totals[k]:8d} lines  ({pct:5.1f}%)")
    print('\nNotes:')
    print('- This is a heuristic only; adjust AI_PATTERNS / TOOL_PATTERNS / FILENAME_GEN_HINTS for better accuracy.')
    print('- Blank lines ignored. Lines can only belong to one bucket.')
    print('- Files with generation filename hints shift human -> tool if no AI markers found.')

if __name__ == '__main__':
    main()
